### ISSUE TITLE
Showing lots of flags in Kirby Starterkit files

### ISSUE THREAD

**Issue by toddz262** [bnomei/kirby3-schema#13]
Not sure what to make of all the flags on files in a working installation of the Kirby Starterkit. Despite everything functioning properly, almost every .yml file I open has some of the following warnings:

- Incorrect type. Expected "string | JSON schema for Kirby 3 CMS blueprint files".
- Missing property "type".
- Property extends is not allowed.

(I'm seeing this despite adding  `blueprint: [page, site, etc.]` to the .yml files.)

I don't know if Kirby is just really forgiving of violations of its own schema, or if the checks being run here are a bit off...

**Comment by bnomei** [comment]
sadly i could not think of an way to support having either a `field with type` or the `extends with reference` while keeping the schema working i all cases.

the extends is a wildcard that references something defined elsewhere.  but a schema is about checking if conditions are met. the schema is just about checking types not about following references across files. kirbys blueprints are flexible with  the extends and their property overwrites but that also means some things can not be checked.

so i decided to keep them flagged as "dangerous". having an `extends: xyz` in your blueprint will (for now) yield a warning in some cases.

an example

**startertkit site/blueprints/pages/home.yml**
```yml
# no type but fields and an extend... what to do with this?
  photography:
    label: Photography
    extends: sections/albums
    status: listed
    size: small
    help: All projects for the homepage are being pulled from the photography page.

  # but a shorthand version with no overwrites would work
  thisworks: sections/albums
```
