### ISSUE TITLE
`writer` not accepted as type on field

### ISSUE THREAD

**Issue by nilsmielke** [bnomei/kirby3-schema#7]
In a page blueprint I have `writer` fields.

```yml
blueprint: page
title: Veranstaltung
tabs:
  # main content
  content:
    columns:
      main:
        width: 2/3
        fields:
          date:
            label: Erster Termin
            type: date
            required: true
          heading:
            label: Seitenüberschrift
            type: writer
            size: small
            inline: true
          text:
            label: Text
            type: writer
            size: large
```

The type as well as the property `inline` get flagged as “not accepted”.

![Bildschirmfoto 2022-07-06 um 10 19 40](https://user-images.githubusercontent.com/8496033/177504338-144f772f-7d21-47ea-9e26-9b1c2f408650.png)

Apart from that, my first impression of the schema is, that it is going to help me understand YAML better so much.
Thank you!
