### ISSUE TITLE
block fieldsets can be objects not just strings

### ISSUE THREAD

**Issue by bnomei** [bnomei/kirby3-schema#9]
https://getkirby.com/docs/reference/plugins/extensions/blocks

```yml
label: "Blöcke"
type: blocks
fieldsets:
  - text
  - gallery
  - video
  pages: # <-----
      name: Sub-Seiten
      fields:
        pages:
          type: pages
          query: page.children

```
